name: LibreTV
slug: libretv
description: LibreTV - 免费在线视频搜索与观看平台
version: 0.0.1
url: https://github.com/LibreSpark/LibreTV
webui: http://[HOST]:[PORT:28899]
panel_icon: mdi:television
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  80/tcp: 28899
map:
  - share
  - media
schema:
  password: password?
options:
  password: ''
